### ISSUE TITLE
Format of `Labels.numpy` output

### ISSUE THREAD

**Issue by calebweinreb** [talmolab/sleap-io#113]
We use `sleap_io` in [keypoint-moseq](https://github.com/dattalab/keypoint-moseq/blob/0c0ca22fe51eda1a16ad67350aef1d062a9e030f/keypoint_moseq/io.py#L1125) to load sleap predictions from `.slp` files. It seems like our implementation is broken because it expects the output of `Labels.numpy()` to have the shape `(n_frames, n_nodes, 2 [or 3])` whereas it actually has the shape `(n_frames, n_tracks, n_nodes, 2 [or 3])`. That's a bug on our end and I'll fix it. 

My question is: why did I ever implement it that way? Was there ever a time when that was the format of the output for single-animal predictions?

**Comment by talmo** [comment]
Hey @calebweinreb,

As far as I can recall, we've always had it rank 4 with a singleton dimension on axis 1 for single-animal data.

Is it possible there was a squeeze or reshape operation somewhere that was getting rid of the singleton dim previously?

Curious since I feel like we used KPMS with both single and multi-animal data in the past with no shape issues.

Let me know if there's anything we can do our end to improve (backwards/forwards)-compatibility!

Talmo

**Comment by calebweinreb** [comment]
Hmm very mysterious. The .h5 loading is fine. Only .slp files seem problematic. Anyway I'll close this issue.
